### ISSUE TITLE
unable to install requirements

### ISSUE THREAD

**Issue by dan9thsense** [Denys88/rl_animal#3]
I tried
pip install -r requirements.txt
but got these errors:
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

**Comment by Denys88** [comment]
Could you confirm please that you are using linux and python >= 3.6?
I am using 'ray' library which is not supported in Windows.

**Comment by dan9thsense** [comment]
Silly me.  I setup a new virtual environment to run this code and somehow ended up with python 3.5.  I recreated the virtual environment with python 3.6 (under ubuntu bionic 18.04.3) and the requirements load just fine.  Sorry to bother you with this one!
