### ISSUE TITLE
directory not found: rl_animal/configs/learning/competition_configurations

### ISSUE THREAD

**Issue by dan9thsense** [Denys88/rl_animal#5]
Player works to run the networks.  I moved on to trying to train.  However, in running `test_ac2` I got a directory not found error from `rl_animal/vecenv.py", line 27, in __init__`

That call goes to hyperparams.py and the line:
LEARNING_DIR =  BASE_DIR + '/configs/learning/competition_configurations/'

However, there is no directory `competition_configurations`

No such file or directory:  rl_animal/configs/learning/competition_configurations

**Comment by Denys88** [comment]
Feel free to use any other configurations. These one could be downloaded from animalai original github.

**Comment by dan9thsense** [comment]
ah, ok, I didn't know what was supposed to go there.  I created the directory and put about 6 sample configurations in there and it looks like it is running.  It opened about 25 arena windows.  I'll leave it running overnight and see what happens.
